### ISSUE TITLE
module 'lusid.models' has no attribute 'UpsertQuotesResponse'

### ISSUE THREAD

**Issue by mneedham** [finbourne/lusid-python-tools#183]
## Bug Report Checklist

- [x] I have checked the existing [documentation](../../../../wiki) for this SDK
- [x] I have searched for any related issues/PRs
- [x] I have read the [LUISD contribution guidelines](../../docs/CONTRIBUTING.md)
- [x] I have read the [LUSID Code of Conduct](../../docs/CODE_OF_CONDUCT.md)

**SDK version**

lusid-sdk==0.11.2376
lusid-sdk-preview==0.11.2376
lusidtools==0.3.40

**Describe the bug**
When I run the help command, I get the following error:

```
$ lusidtools --help

Traceback (most recent call last):
  File "/home/markhneedham/anaconda3/bin/lusidtools", line 5, in <module>
    from lusidtools.commands.commands import main
  File "/home/markhneedham/anaconda3/lib/python3.8/site-packages/lusidtools/__init__.py", line 1, in <module>
    import lusidtools.cocoon.cocoon
  File "/home/markhneedham/anaconda3/lib/python3.8/site-packages/lusidtools/cocoon/__init__.py", line 1, in <module>
    import lusidtools.cocoon.cocoon
  File "/home/markhneedham/anaconda3/lib/python3.8/site-packages/lusidtools/cocoon/cocoon.py", line 21, in <module>
    class BatchLoader:
  File "/home/markhneedham/anaconda3/lib/python3.8/site-packages/lusidtools/cocoon/cocoon.py", line 101, in BatchLoader
    ) -> lusid.models.UpsertQuotesResponse:
AttributeError: module 'lusid.models' has no attribute 'UpsertQuotesResponse'
```

I think the reason might be that the `UpsertQuotesResponse` file hasn't been added to the SDK package. At least I can't see it on the list of model files here - https://github.com/finbourne/lusid-sdk-python/tree/master/sdk/lusid/models

**Comment by rizwansaeed** [comment]
Hi Mark,

Please could you try removing the lusid-sdk package and just keep the lusid-sdk-preview one.

We currently classify our APIs by their maturity level as described here: https://www.lusid.com/app/resources/documentation/lifecycle. 

Only the EAP and Production are in the lusid-sdk package but all of them are in the lusid-sdk-preview package. Currently the UpsertQuotes API has a Beta classification which means it is in the preview package only. Note we are planning to move most of these APIs to Production in early Q1 at which point they will be in the lusid-sdk package.
